Repository boa-dev/boa-dev.github.io, pull requests merged in 2024-04, with the labels that each got.

#147 Remove all references to the development docs
  blog/2023-07-08-boa-release-17.md
  docs/contributing/CONTRIBUTING.md
  docusaurus.config.ts
  src/components/home/index.tsx
Labels: documentation, enhancement

#150 Refactor Conformance page to allow back and forward history
  src/components/HomepageFeatures/index.tsx
  src/components/benchmarks/index.tsx
  src/components/conformance/HeroBanner/index.tsx
  src/components/conformance/HeroBanner/styles.module.css
  src/components/conformance/ResultsDisplay/components/SuiteDataContainer/cards/TestGrid/index.tsx
  src/components/conformance/ResultsDisplay/components/SuiteDataContainer/index.tsx
  src/components/conformance/ResultsDisplay/components/SuiteDisplay/index.tsx
  src/components/conformance/ResultsDisplay/components/SuiteSelector/index.tsx
  src/components/conformance/ResultsDisplay/index.tsx
  src/components/conformance/ResultsDisplay/nav.tsx
  src/components/conformance/VersionSelector/index.tsx
  src/components/conformance/index.tsx
  src/components/conformance/types.ts
  src/components/conformance/utils.ts
  src/components/latestPosts/latestPosts.tsx
  src/pages/conformance/index.tsx
Labels: enhancement

#153 Filter out empty suite results for version
  src/components/conformance/ResultsDisplay/components/SuiteSelector/index.tsx
  src/components/conformance/ResultsDisplay/nav.tsx
Labels: bug

#155 Fallback to full stats if the versioned stats don't exist
  src/components/conformance/ResultsDisplay/components/SuiteSelector/index.tsx
Labels: bug
