Repository boa-dev/boa-dev.github.io, pull requests merged in 2024-06, with the labels that each got.

#152 Add aria-label and grid header on test hover
  src/components/conformance/ResultsDisplay/components/SuiteDataContainer/cards/TestGrid/index.tsx
  src/components/conformance/ResultsDisplay/components/SuiteDataContainer/cards/TestGrid/styles.module.css
Labels: enhancement

#159 Fix prop mutation and address some lints
  src/components/conformance/ResultsDisplay/components/SuiteDataContainer/cards/TestGrid/index.tsx
  src/components/conformance/ResultsDisplay/components/SuiteSelector/index.tsx
  src/components/conformance/ResultsDisplay/index.tsx
  src/components/conformance/ResultsDisplay/nav.tsx
  src/components/conformance/utils.ts
  src/pages/conformance/index.tsx
  tsconfig.json
Labels: bug, enhancement

#161 Bump docusaurus to v3.4.0
  package-lock.json
  package.json
Labels: dependencies
